// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import ()

type Image struct {
	ID        int64  `json:"id"`
	UserID    int64  `json:"user_id"`
	ImagePath string `json:"image_path"`
	ImageUrl  string `json:"image_url"`
}

type User struct {
	ID             int64  `json:"id"`
	Username       string `json:"username"`
	HashedPassword string `json:"hashed_password"`
}
